/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// remote719_db.h

#pragma once

#define __UUID_REMOTE                         0x4e, 0x9f, 0x07, 0x38, 0x96, 0xa8, 0x46, 0x02, 0x8a, 0x5c, 0xe9, 0x8e, 0x84, 0x60, 0x0c, 0xd2
#define __UUID_REMOTE_PADDLE                  0x88, 0x46, 0x09, 0x3d, 0xcf, 0xfe, 0x43, 0x7a, 0xba, 0xbe, 0x77, 0x41, 0x20, 0xca, 0xb0, 0x34

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'remote'
#define HDLS_REMOTE                           0x0028
// ----- Characteristic 'paddle'
#define HDLC_REMOTE_PADDLE                    0x0029
#define HDLC_REMOTE_PADDLE_VALUE              0x002A

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table remote719_gatt_db_ext_attr_tbl[];
extern const uint16_t remote719_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;
